import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { AppProviders } from "@/services/clerk/components/AppProvider";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${outfitSans.variable} antialiased font-sans`}>
        {/* Wrap client-only logic inside a client component */}
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
